# config.py
INDICATOR_DESCRIPTIONS = {
        "STATEFP": "State FIPS code",
        "COUNTYFP": "County FIPS number",
        "TRACTCE": "Census tract code",
        "AFFGEOID": "Census tract identifier",
        "GEOID": "County Identifier",
        "COUNTY": "County Name",
        "StateAbbr": "State Abbreviation",
        "StateDesc": "Full State Name",
        "Location": "Location Description",
        "E_TOTPOP": "Population Estimate",
        "M_TOTPOP": "Population Estimate MOE",
        "E_DAYPOP": "Estimated Daytime Population",
        "SPL_EJI": "Summation of the EBM, HVM, and SVI module percentile ranks",
        "RPL_EJI": "Percentile ranks of SPL_EJI",
        "SPL_SER": "Summation of the EB, and SV module percentile ranks",
        "RPL_SER": "Percentile ranks of SPL_SER",
        "EPL_OZONE": "Percentile rank of annual mean days above O3 regulatory standard",
        "EPL_PM": "Percentile rank of annual mean days above PM2.5 regulatory standard",
        "EPL_DSLPM": "Percentile rank of ambient concentrations of diesel PM/m3",
        "EPL_TOTCR": "Percentile rank of the probability of contracting cancer",
        "SPL_EBM_THEME1": "Domain consisting of ozone, PM2.5, air toxics cancer risk, and diesel particulate matter",
        "RPL_EBM_DOM1": "Percentile rank of domain consisting of ozone, PM2.5, air toxics cancer risk, and diesel particulate matter",
        "EPL_NPL": "Percentile rank of proportion of tract's area within 1-mi buffer of EPA National Priority List site",
        "EPL_TRI": "Percentile rank of proportion of tract's area within 1-mi buffer of EPA Toxic Release Inventory site",
        "EPL_TSD": "Percentile rank of proportion of tract's area within 1-mi buffer of EPA Treatment, Storage, and Disposal site",
         "EPL_RMP": "Percentile rank of proportion of tract's area within 1-mi buffer of EPA risk management plan site",
        "EPL_COAL": "Percentile rank of proportion of tract's area within 1-mi buffer of coal mines",
        "EPL_LEAD": "Percentile rank of proportion of tract's area within 1-mi buffer of lead mines",
        "SPL_EBM_THEME2": "Domain consisting of proximity to national priority list sites, proximity to release inventory sites, proximity to treatment, storage, and disposal sites, proximity to risk management plan sites, proximity to coal mines, and proximity to lead mines",
       "RPL_EBM_DOM2": "Percentile rank of domain consisting of proximity to national priority list sites, proximity to release inventory sites, proximity to treatment, storage, and disposal sites, proximity to risk management plan sites, proximity to coal mines, and proximity to lead mines",
       "EPL_PARK": "Percentile rank of proportion of tract's area within 1-mi buffer of green space",
        "EPL_HOUAGE": "Percentile rank of percentage of houses built pre-1980 (lead exposure)",
        "EPL_WLKIND": "Percentile rank of a nationwide geographic data resource that ranks block groups according to their relative walkability",
        "SPL_EBM_THEME3": "Domain consisting of proximity to recreational parks, houses built pre-1980 (lead exposure), and walkability index",
        "RPL_EBM_DOM3": "Percentile rank of domain consisting of proximity to recreational parks, houses built pre-1980 (lead exposure), and walkability index",
       "EPL_RAIL": "Percentile rank of proportion of tract's area within 1-mi buffer of railroad",
       "EPL_ROAD": "Percentile rank of proportion of tract's area within 1-mi buffer of high-volume road or highway",
       "EPL_AIRPRT": "Percentile rank of proportion of tract's area within 1-mi buffer of airport",
        "SPL_EBM_THEME4": "Domain consisting of proximity to high volume roads, proximity to railways, and proximity to airports",
       "RPL_EBM_DOM4": "Percentile rank of domain consisting of proximity to high volume roads, proximity to railways, and proximity to airports",
        "EPL_IMPWTR": "Percentile rank of percent of tract that intersects an impaired/impacted watershed at the HUC12 level",
       "SPL_EBM_THEME5":"Domain consisting of impaired water bodies",
       "RPL_EBM_DOM5": "Percentile rank of domain consisting of impaired water bodies",
       "SPL_EBM": "The environmental burden module percentile ranks",
        "RPL_EBM": "The environmental burden module percentile ranks",
       "EPL_MINRTY":"Percentile rank of percentage of minority persons",
       "SPL_SVM_DOM1":"Domain consisting of percentage of individuals who are a racial/ethnic minority",
        "RPL_SVM_DOM1":"Percentile rank of domain consisting of percentage of individuals who are a racial/ethnic minority",
       "EPL_POV200": "Percentile rank of percentage below 200% poverty",
        "EPL_NOHSDP":"Percentile rank of percentile Percentage of persons with no high school diploma (age 25+) estimate",
       "EPL_UNEMP":"Percentile rank of percentage of persons who are unemployed",
        "EPL_RENTER":"Percentile rank of percentage of persons who rent",
       "EPL_HOUBDN":"Percentile rank of percentage of households that make less than 75,000",
        "EPL_UNINSUR": "Percentile rank of percentage of persons who are uninsured",
        "EPL_NOINT": "Percentile rank of percentage of persons without internet",
        "SPL_SVM_DOM2": "Domain consisting of below 200% poverty, no high school diploma, unemployed, housing tenure, housing cost, no health insurance, and not internet",
         "RPL_SVM_DOM2":"Percentile rank of domain consisting of below 200% poverty, no high school diploma, unemployed, housing tenure, housing cost, no health insurance, and not internet",
        "EPL_AGE65": "Percentile rank of percentage of persons aged 65 and older estimate",
         "EPL_AGE17":"Percentile rank of percentage of persons aged 17 and younger estimate",
        "EPL_DISABL":"Percentile rank of percentage of civilian noninstitutionalized population with a disability estimate",
        "SPL_SVM_DOM3": "Domain consisting of English language proficiency, aged 65 or older, aged 17 or younger, and civilian with a disability",
        "RPL_SVM_DOM3": "Percentile rank of domain consisting of English language proficiency, aged 65 or older, aged 17 or younger, and civilian with a disability",
        "EPL_MOBILE":"Percentile rank of percentage of mobile homes estimate",
       "EPL_GROUPQ": "Percentile rank of percentage of persons in group quarters estimate",
        "SPL_SVM_DOM4": "Domain consisting of number of mobile homes and housing with group quarters",
       "RPL_SVM_DOM4": "Percentile rank of domain consisting of number of mobile homes and housing with group quarters",
        "SPL_SVM": "Social vulnerability module percentile rank",
        "RPL_SVM": "Social vulnerability module percentile rank",
        "F_BPHIGH": "Flag indicating tracts greater than 0.6666 percentile rank with high blood pressure",
        "F_ASTHMA": "Flag indicating tracts greater than 0.6666 percentile rank with asthma",
        "F_CANCER": "Flag indicating tracts greater than 0.6666 percentile rank with cancer",
        "F_MHLTH": "Flag indicating tracts greater than 0.6666 percentile rank with not good mental health",
        "F_DIABETES":"Flag indicating tracts greater than 0.6666 percentile rank with diabetes",
         "F_HVM": "Total number of tertile flags",
         "RPL_HVM": "Percentile rank of combined tertile flags",
        "EP_BPHIGH": "Percentage of individuals with Raw high blood pressures values",
        "EP_ASTHMA": "Percentage of individuals with asthma",
        "EP_CANCER": "Percentage of individuals with cancer",
         "EP_MHLTH": "Percentage of individual reporting not good mental health",
        "EP_DIABETES": "Percentage of individuals with diabetes",
        "EPL_BPHIGH":"Percentile rank of percentage of individuals with Raw high blood pressures values",
         "EPL_ASTHMA": "Percentile rank of percentage of individuals with asthma",
         "EPL_CANCER": "Percentile rank of percentage of persons with cancer",
        "EPL_MHLTH": "Percentile rank of percentage of individual reporting not good mental health percentile rank",
         "EPL_DIABETES": "Percentile rank of percentage of individuals with diabetes",
        "E_DSLPM": "Ambient concentrations of diesel PM/m3",
        "E_TOTCR": "The probability of contracting cancer",
        "E_NPL":"Proportion of tract's area within 1-mi buffer of EPA National Priority List site",
         "E_TRI":"Proportion of tract's area within 1-mi buffer of EPA Toxic Release Inventory site",
        "E_TSD": "Proportion of tract's area within 1-mi buffer of EPA Treatment, Storage, and Disposal site",
        "E_RMP": "Proportion of tract's area within 1-mi buffer of EPA risk management plan site",
        "E_COAL":"Proportion of tract's area within 1-mi buffer of coal mines",
        "E_LEAD":"Proportion of tract's area within 1-mi buffer of lead mines",
       "E_PARK":"Proportion of tract's area within 1-mi buffer of green space",
       "E_RAIL":"Proportion of tract's area within 1-mi buffer of railroad",
       "E_ROAD":"Proportion of tract's area within 1-mi buffer of high-volume road or highway",
       "E_AIRPRT":"Proportion of tract's area within 1-mi buffer of airport",
      "E_IMPWTR":"Percent of tract that intersects an impaired/impacted watershed at the HUC12 level"
}